### ISSUE TITLE
error after create lxc container

### ISSUE THREAD

**Issue by tediorelee** [ich777/unraid-lxc-plugin#15] opened 2024-12-22 11:18 UTC
```
 syntax error, unexpected '=' in /boot/config/plugins/lxc/plugin.cfg on line 8 in /usr/local/emhttp/plugins/dynamix/include/PageBuilder.php(58) : eval()'d code on line 1
```

Hi I'm getting this error after installed one debian lxc, any clues would be helpful.

Env: Unraid Plus with version 6.11.5

![image](https://github.com/user-attachments/assets/20175c95-90ef-4910-803e-fb9e04fde583)

**Comment by ich777** [comment] 2024-12-22 14:34
@tediorelee please post your Diagnostics, this is to less information.

**Comment by tediorelee** [comment] 2024-12-23 04:47
Kindly check. 
[tower-diagnostics-20241223-1246.zip](https://github.com/user-attachments/files/18225180/tower-diagnostics-20241223-1246.zip)

**Comment by ich777** [comment] 2024-12-23 07:09
@tediorelee ah sorry, I completely missed that you are on 6.11.5 since there is not much useful information in the Diagnostics to look into that.

May I ask why are you on such an old version? We are just on the verge of Unraid 7.0.0

Can you please do:
```
cat /boot/config/plugins/lxc/plugin.cfg
```
from an Unraid terminal and post the output?

Seems like something in your config file is wrong, line 8 should be the Backup path, do you maybe have a additional `=` in the path?

However I would strongly recommend to upgrade to Unraid 6.12.14

**Comment by tediorelee** [comment] 2024-12-23 07:23
```
SERVICE=disabled
BDEVTYPE=dir
TIMEOUT=15
AUTOSTART_DELAY=10
DYNAMIC_STATS=enabled
LXC_CONTAINER_URL=images.linuxcontainers.org
LXC_BACKUP_SERVICE=disabled
LXC_BACKUP_PATH=LXC_BACKUP_KEEP=
LXC_BACKUP_KEEP=LXC_BACKUP_THREADS=
LXC_BACKUP_THREADS=LXC_BACKUP_COMPRESSION=
LXC_BACKUP_COMPRESSION=LXC_BACKUP_USE_SNAPSHOT=
LXC_BACKUP_USE_SNAPSHOT=LXC_GITHUB_USER=
LXC_GITHUB_USER=
LXC_GITHUB_TOKEN=
```
Seems like `LXC_BACKUP_PATH` is not correct.

(I'm just too lazy to uprade my system since it's working completely fine and thanks for your advice I will try to upgrade to latest version)

**Comment by ich777** [comment] 2024-12-23 07:42
> LXC_BACKUP_PATH=LXC_BACKUP_KEEP=
> LXC_BACKUP_KEEP=LXC_BACKUP_THREADS=
> LXC_BACKUP_THREADS=LXC_BACKUP_COMPRESSION=
> LXC_BACKUP_COMPRESSION=LXC_BACKUP_USE_SNAPSHOT=
> LXC_BACKUP_USE_SNAPSHOT=LXC_GITHUB_USER=

Please correct those variables, don't know how that happened.

I'll take a look into this on my development machine.

**Comment by ich777** [comment] 2024-12-23 07:56
@tediorelee I can reproduce this now but this only happens if I set the backup function to Yes, then No and then Apply which is a real corner case in my opinion.

However to fix that just set it once to Yes, Apply, then delete the two entries, set it to No and hit Apply again:
![Peek 2024-12-23 08-53](https://github.com/user-attachments/assets/cdd97adb-fd6e-4d28-96cb-df9d65780079)

**Comment by tediorelee** [comment] 2024-12-23 08:47
Hi, just quickly upgrade my system to Unraid 6.12.14 and come back.

(met a little bit issue and my webgui is lost, cost me one hour to get it back ;( )

Change to **No** and **Yes** again can fix this issue, seems working fine now, thanks a lot anyway!

![image](https://github.com/user-attachments/assets/3b2d51ad-8a04-47d6-8b7b-533c8069aa6a)

**Comment by ich777** [comment] 2024-12-23 08:48
@tediorelee glad that it is working now, I'll look into that and probably push a fix for that issue.

If that is solved for you, are you okay closing this issue?

**Comment by tediorelee** [comment] 2024-12-23 08:49
Yes, thanks.

**Closed as completed** 2024-12-23 08:51 UTC

**Comment by ich777** [comment] 2024-12-23 12:58
@tediorelee just as a follow up, this issue is now fixed and shouldn't happen with the newest update `2024-12-23` any more.

**Comment by tediorelee** [comment] 2024-12-23 13:09
> @tediorelee just as a follow up, this issue is now fixed and shouldn't happen with the newest update `2024-12-23` any more.

that was quick，I will update to latest version :)
